const crypto = require('crypto'); const bcrypt = require('bcryptjs'); const jwt = require('jsonwebtoken'); const { z } = require('zod'); const db = require('../config/db');
const registration = z.object({ email: z.string().email().max(254).transform(v => v.toLowerCase()), password: z.string().min(12).max(128), displayName: z.string().trim().min(2).max(80), referralCode: z.string().trim().min(4).max(32).optional() });
const credentials = z.object({ email: z.string().email().transform(v => v.toLowerCase()), password: z.string().min(1).max(128) });
const createToken = user => jwt.sign({ sub: user.id, role: user.role, email: user.email }, process.env.JWT_SECRET, { expiresIn: '30m', issuer: 'nova-lift-api', audience: 'nova-lift' });
const newReferralCode = () => crypto.randomBytes(5).toString('hex').toUpperCase();

exports.register = async (req, res, next) => { const parsed = registration.safeParse(req.body); if (!parsed.success) return res.status(422).json({ error: 'Invalid registration details.', details: parsed.error.flatten() }); const { email,password,displayName,referralCode }=parsed.data; const client=await db.connect(); try { await client.query('BEGIN'); const referrer=referralCode ? (await client.query('SELECT id FROM users WHERE referral_code=$1 AND status=$2',[referralCode,'active'])).rows[0] : null; if (referralCode && !referrer) { await client.query('ROLLBACK'); return res.status(422).json({error:'Referral code is not valid.'}); } const hash=await bcrypt.hash(password, 12); const user=(await client.query('INSERT INTO users (email,password_hash,display_name,referral_code,referred_by) VALUES ($1,$2,$3,$4,$5) RETURNING id,email,display_name,role,status',[email,hash,displayName,newReferralCode(),referrer?.id||null])).rows[0]; const rawToken=crypto.randomBytes(32).toString('base64url'); await client.query('INSERT INTO email_verification_tokens (user_id,token_hash,expires_at) VALUES ($1,$2,now() + interval \'24 hours\')',[user.id,crypto.createHash('sha256').update(rawToken).digest('hex')]); await client.query('INSERT INTO audit_events (id,actor_id,action,entity_type,entity_id,metadata) VALUES ($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),user.id,'user.registered','user',user.id,JSON.stringify({referralUsed:Boolean(referrer)})]); await client.query('COMMIT'); const payload={ message:'Account created. Verify the email address to sign in.', user:{id:user.id,email:user.email,status:user.status} }; if(process.env.NODE_ENV !== 'production') payload.verificationToken=rawToken; return res.status(201).json(payload); } catch(e) { await client.query('ROLLBACK'); if(e.code==='23505') return res.status(409).json({error:'Email address is already registered.'}); next(e); } finally { client.release(); } };
exports.verifyEmail = async (req,res,next) => { const token=z.string().min(20).safeParse(req.body?.token); if(!token.success) return res.status(422).json({error:'Verification token required.'}); const tokenHash=crypto.createHash('sha256').update(token.data).digest('hex'); const client=await db.connect(); try { await client.query('BEGIN'); const record=(await client.query('SELECT user_id FROM email_verification_tokens WHERE token_hash=$1 AND used_at IS NULL AND expires_at>now() FOR UPDATE',[tokenHash])).rows[0]; if(!record){await client.query('ROLLBACK'); return res.status(400).json({error:'Verification link is invalid or expired.'});} await client.query('UPDATE email_verification_tokens SET used_at=now() WHERE token_hash=$1',[tokenHash]); const user=(await client.query("UPDATE users SET status='active', email_verified_at=now(), updated_at=now() WHERE id=$1 RETURNING id,email,role",[record.user_id])).rows[0]; await client.query('INSERT INTO audit_events (id,actor_id,action,entity_type,entity_id) VALUES ($1,$2,$3,$4,$5)',[crypto.randomUUID(),user.id,'user.email_verified','user',user.id]); await client.query('COMMIT'); res.json({token:createToken(user), user}); } catch(e){await client.query('ROLLBACK'); next(e);} finally {client.release();} };
exports.login = async (req,res,next) => { const parsed=credentials.safeParse(req.body); if(!parsed.success) return res.status(422).json({error:'Email and password are required.'}); try { const user=(await db.query('SELECT id,email,password_hash,display_name,role,status FROM users WHERE email=$1',[parsed.data.email])).rows[0]; if(!user || !await bcrypt.compare(parsed.data.password,user.password_hash)) return res.status(401).json({error:'Invalid email or password.'}); if(user.status!=='active') return res.status(403).json({error:'Verify your email or contact support.'}); await db.query('UPDATE users SET last_login_at=now(),updated_at=now() WHERE id=$1',[user.id]); res.json({token:createToken(user),user:{id:user.id,email:user.email,displayName:user.display_name,role:user.role}}); } catch(e){next(e);} };
