-- Starter catalog: 40 non-financial work and product tasks.
INSERT INTO tasks (title, description, category, estimated_minutes) VALUES
('Complete your profile', 'Add a display name and verify your contact preferences.', 'Getting started', 5),
('Read platform guidelines', 'Review the community and acceptable-use guidelines.', 'Getting started', 8),
('Set notification preferences', 'Choose which product and account notifications you receive.', 'Getting started', 4),
('Explore the help centre', 'Find answers to three common account questions.', 'Getting started', 10),
('Accessibility check', 'Review the interface with keyboard navigation and report issues.', 'Quality', 15),
('Mobile navigation review', 'Test the main navigation on a mobile device.', 'Quality', 10),
('Broken-link check', 'Check an assigned page and report any broken links.', 'Quality', 12),
('Form clarity review', 'Review an assigned form for clear labels and instructions.', 'Quality', 15),
('Homepage feedback', 'Share focused feedback on the homepage layout.', 'Research', 10),
('Feature survey', 'Complete a short survey about a proposed feature.', 'Research', 8),
('Onboarding interview', 'Answer structured questions about the sign-up experience.', 'Research', 20),
('Search relevance review', 'Rate the relevance of sample search results.', 'Research', 12),
('Write a help article outline', 'Draft an outline for a short help-centre article.', 'Content', 25),
('Improve a FAQ answer', 'Make an existing FAQ answer clearer and more concise.', 'Content', 15),
('Create image alt text', 'Write descriptive alternative text for five assigned images.', 'Content', 12),
('Proofread a product update', 'Check spelling, grammar, and clarity in a short update.', 'Content', 15),
('Categorise customer feedback', 'Tag ten feedback items by topic.', 'Operations', 15),
('Review support response templates', 'Review templates for tone and completeness.', 'Operations', 20),
('Validate a data entry sample', 'Compare assigned records with their source information.', 'Operations', 18),
('Check knowledge-base labels', 'Confirm labels match their help-centre content.', 'Operations', 12),
('Create a weekly plan', 'Set goals and milestones for the coming week.', 'Productivity', 10),
('Organise saved items', 'Group saved materials into useful collections.', 'Productivity', 10),
('Set up a workspace checklist', 'Create a checklist for a repeatable workflow.', 'Productivity', 15),
('Review your activity history', 'Check recent activity and flag anything unexpected.', 'Productivity', 8),
('Test account recovery instructions', 'Review recovery instructions for clarity; do not change account credentials.', 'Security', 10),
('Review privacy settings', 'Review available privacy settings and note improvements.', 'Security', 12),
('Identify suspicious-message signs', 'Complete a short awareness exercise about phishing indicators.', 'Security', 8),
('Secure-password checklist', 'Review password hygiene guidance and account security options.', 'Security', 7),
('Compare two product descriptions', 'Identify factual differences between two approved descriptions.', 'Catalog', 12),
('Tag catalog attributes', 'Apply approved category tags to five catalog items.', 'Catalog', 15),
('Check product metadata', 'Validate titles, descriptions, and categories for assigned items.', 'Catalog', 18),
('Suggest catalog keywords', 'Suggest search keywords for an approved catalog item.', 'Catalog', 10),
('Welcome new community members', 'Prepare a friendly, approved welcome message.', 'Community', 8),
('Moderation guideline quiz', 'Complete a quiz on community moderation rules.', 'Community', 10),
('Event feedback form', 'Complete feedback for a community event.', 'Community', 7),
('Community resource review', 'Review a shared community resource for relevance.', 'Community', 15),
('Try a new dashboard view', 'Use a dashboard view and report any usability concerns.', 'Product testing', 12),
('Review empty-state wording', 'Assess wording shown when no data is available.', 'Product testing', 8),
('Check notification timing', 'Review a sample notification schedule for clarity.', 'Product testing', 10),
('Submit an improvement idea', 'Submit one structured improvement suggestion with context.', 'Product testing', 10);
