import { useEffect, useMemo, useState } from 'react';
import * as api from '../services/api';
const nav = [['overview','Overview'],['tasks','Task orders'],['wallet','Wallet'],['finance','Deposits & withdrawals'],['referrals','Referrals'],['notifications','Notifications'],['support','Support'],['profile','Profile']];
const money = (v) => `$${Number(v || 0).toLocaleString(undefined,{minimumFractionDigits:2})}`;
function Card({children,className=''}){return <section className={`table-card ${className}`}>{children}</section>}
function Rows({rows,empty='Nothing here yet'}){return rows?.length ? rows.map((r)=><div className="list-row" key={r.id||JSON.stringify(r)}><div><strong>{r.name||r.title||r.description||r.type||'Activity'}</strong><small>{r.createdAt||r.status||r.note||'Recently updated'}</small></div><b className={Number(r.amount)>0?'positive':''}>{r.amount !== undefined ? money(r.amount) : r.status || 'View'}</b></div>) : <div className="empty"><h3>{empty}</h3><p>New activity from your account will appear here.</p></div>}
export default function Home(){const [page,setPage]=useState('overview');const [data,setData]=useState({wallet:null,tasks:[],orders:[],transactions:[],referrals:null,deposits:[],withdrawals:[],notifications:[],support:[]});const [notice,setNotice]=useState('');useEffect(()=>{Promise.all([api.getWallet(),api.getTasks(),api.getTaskOrders(),api.getTransactions(),api.getReferrals(),api.getDeposits(),api.getWithdrawals(),api.getNotifications(),api.getSupport()]).then(([wallet,tasks,orders,transactions,referrals,deposits,withdrawals,notifications,support])=>setData({wallet,tasks,orders,transactions,referrals,deposits,withdrawals,notifications,support}))},[]);const title=nav.find(([id])=>id===page)?.[1];const act=async(fn,message)=>{try{await fn();setNotice(message)}catch{setNotice('The SQL Server API rejected this request.')}};return <div className="app-shell"><aside className="user-sidebar"><div className="logo">nova<span>lift</span></div><div className="profile-mini"><div className="avatar">AM</div><div><strong>Alex Morgan</strong><small>VIP Level 2</small></div></div><nav>{nav.map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><span className={`nav-icon ${id}`}/>{label}</button>)}</nav><div className="sidebar-foot"><i/> SQL Server API ready</div></aside><main className="user-main"><header className="topbar"><div><p className="eyebrow">MEMBER PORTAL</p><h1>{title}</h1></div><button className="notification" onClick={()=>setPage('notifications')}>◎</button></header>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}{page==='overview'&&<Overview d={data} go={setPage}/>} {page==='tasks'&&<Tasks d={data} act={act}/>} {page==='wallet'&&<Wallet d={data}/>} {page==='finance'&&<Finance d={data} act={act}/>} {page==='referrals'&&<Referrals d={data}/>} {page==='notifications'&&<Card><h2>Notifications</h2><Rows rows={data.notifications} empty="You are all caught up"/></Card>} {page==='support'&&<Support d={data} act={act}/>} {page==='profile'&&<Profile act={act}/>}</main><div className="mobile-nav">{nav.slice(0,5).map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}>{label}</button>)}</div></div>}
function Metric({label,value,accent}){return <article className={`metric ${accent}`}><span>{label}</span><strong>{value}</strong><small>Live account data</small></article>}
function Overview({d,go}){return <><section className="welcome"><div><p className="eyebrow">MEMBER OVERVIEW</p><h2>Good morning, Alex</h2><p>Complete tasks today and grow your commission balance.</p></div></section><div className="metric-grid"><Metric label="Available balance" value={money(d.wallet?.balance)} accent="mint"/><Metric label="Today&apos;s earnings" value={money(d.wallet?.todayCommission)} accent="blue"/><Metric label="Total commission" value={money(d.wallet?.totalCommission)} accent="peach"/></div><div className="section-heading"><div><p className="eyebrow">RECOMMENDED FOR YOU</p><h2>Available task orders</h2></div><button className="text-button" onClick={()=>go('tasks')}>View all →</button></div><div className="task-grid">{d.tasks.slice(0,3).map(t=><TaskCard key={t.id} task={t}/>)}</div><Card><div className="section-heading"><h2>Recent activity</h2><button className="text-button" onClick={()=>go('wallet')}>Open wallet</button></div><Rows rows={d.transactions.slice(0,4)}/></Card></>}
function TaskCard({task,onStart}){return <article className="task-card"><div className="task-top"><span className="task-symbol">✦</span><span className="status">Available</span></div><h3>{task.name}</h3><p>{task.description}</p><div className="task-meta"><span>Reward <b>{money(task.commission)}</b></span><span>Level {task.requiredLevel||1}+</span></div><button className="primary-button" onClick={onStart}>Start task <span>→</span></button></article>}
function Tasks({d,act}){return <><div className="filter-row"><span className="muted">{d.tasks.length} available tasks</span></div><div className="task-grid">{d.tasks.map(t=><TaskCard key={t.id} task={t} onStart={()=>act(()=>api.startTask(t.id),'Task started. Complete it to receive commission.')}/>)}</div><Card><h2>Task order history</h2><Rows rows={d.orders} empty="No task orders yet"/></Card></>}
function Wallet({d}){return <><section className="wallet-hero"><div><p className="eyebrow">TOTAL AVAILABLE</p><strong>{money(d.wallet?.balance)}</strong><p>Ready to withdraw</p></div></section><Card><h2>Wallet transactions</h2><Rows rows={d.transactions} empty="No transactions yet"/></Card></>}
function Finance({d,act}){return <><div className="metric-grid"><Metric label="Deposits" value={d.deposits.length} accent="mint"/><Metric label="Withdrawals" value={d.withdrawals.length} accent="peach"/></div><Card><div className="section-heading"><h2>Deposit history</h2><button className="primary-button" onClick={()=>act(()=>api.createDeposit({amount:100,paymentMethodId:1}),'Deposit submitted for review.')}>New deposit</button></div><Rows rows={d.deposits} empty="No deposits yet"/></Card><Card><div className="section-heading"><h2>Withdrawal history</h2><button className="primary-button" onClick={()=>act(()=>api.createWithdrawal({amount:50,paymentMethodId:1}),'Withdrawal submitted for review.')}>Request withdrawal</button></div><Rows rows={d.withdrawals} empty="No withdrawals yet"/></Card></>}
function Referrals({d}){return <><div className="metric-grid"><Metric label="Total referrals" value={d.referrals?.totalReferrals||0} accent="mint"/><Metric label="Active referrals" value={d.referrals?.activeReferrals||0} accent="blue"/><Metric label="Referral earnings" value={money(d.referrals?.totalCommission)} accent="peach"/></div><Card className="invite-card"><p className="eyebrow">YOUR INVITE CODE</p><h2>INVITE-ALEX-24</h2><p>Share your code and earn commission from every active referral.</p><button className="primary-button" onClick={()=>navigator.clipboard?.writeText('INVITE-ALEX-24')}>Copy code</button></Card></>}
function Support({d,act}){return <Card><div className="section-heading"><h2>Support tickets</h2><button className="primary-button" onClick={()=>act(()=>api.createSupport({subject:'New support request',message:'Please contact me.'}),'Support ticket created.')}>New ticket</button></div><Rows rows={d.support} empty="No support tickets"/></Card>}
function Profile({act}){return <Card className="profile-card"><div className="profile-large avatar">AM</div><h2>Alex Morgan</h2><p className="muted">alex.morgan@example.com</p><div className="form-grid"><label>Full name<input defaultValue="Alex Morgan"/></label><label>Phone number<input placeholder="Add phone number"/></label><label>Language<select defaultValue="en"><option value="en">English</option><option value="my">မြန်မာ</option><option value="th">ไทย</option><option value="zh">中文</option></select></label></div><button className="primary-button" onClick={()=>act(()=>api.updateProfile({fullName:'Alex Morgan'}),'Profile saved.')}>Save changes</button></Card>}
